Ext.define('Console.model.CpsUserAccount', {
	extend: 'Ext.data.Model',
	fields: [
    	{
    		name: 'user_name',
    		type: 'string'
    	}, {
    		name: 'device_app_id',
    		type: 'string'
    	}, {
    		name: 'user_app_version',
    		type: 'string'
    	}, {
    		name: 'user_license',
    		type: 'string'
    	}, {
    		name: 'user_device_id',
    		type: 'string'
    	}, {
    		name: 'user_corp_id',
    		type: 'string'
    	}, {
    		name: 'user_organization_id',
    		type: 'string'
    	}, {
    		name: 'user_workgroup_id',
    		type: 'string'
    	}, {
    		name: 'user_role',
    		type: 'string'
    	}, {
    		name: 'user_firstname_en',
    		type: 'string'
    	}, {
    		name: 'user_lastname_en',
    		type: 'string'
    	}, {
    		name: 'user_firstname_tw',
    		type: 'string'
    	}, {
    		name: 'user_lastname_tw',
    		type: 'string'
    	}, {
    		name: 'user_nickname',
    		type: 'string'
    	}, {
    		name: 'user_photo',
    		type: 'string'
    	}, {
    		name: 'user_phone_number_1',
    		type: 'string'
    	}, {
    		name: 'user_phone_number_2',
    		type: 'string'
    	}, {
    		name: 'user_mobile_number_1',
    		type: 'string'
    	}, {
    		name: 'user_mobile_number_2',
    		type: 'string'
    	}, {
    		name: 'user_email_1',
    		type: 'string'
    	}, {
    		name: 'user_email_2',
    		type: 'string'
    	}, {
    		name: 'user_id',
    		type: 'string'
    	}, {
    		name: 'gender',
    		type: 'string'
    	}, {
    		name: 'birthday',
    		type: 'string'
    	}, {
    		name: 'mobile_country',
    		type: 'string'
    	}, {
    		name: 'address_zip',
    		type: 'string'
    	}, {
    		name: 'address_city',
    		type: 'string'
    	}, {
    		name: 'address_county',
    		type: 'string'
    	}, {
    		name: 'address_road_no',
    		type: 'string'
    	}, {
    		name: 'registration_date',
    		type: 'string'
    	}, {
    		name: 'last_updated_date',
    		type: 'string'
    	}, {
    		name: 'last_connected_date',
    		type: 'string'
    	}, {
            name: 'user_security',
            type: 'string'
        }, {
    		name: 'user_status',
    		type: 'string'
    	}, {
    		name: 'operator',
    		type: 'string'
    	}, {
            name: 'organization_parent_id',
            type: 'string'
        }, {
    		name: 'organization_id',
    		type: 'string'
    	}, {
    		name: 'organization_id_ch',
    		type: 'string'
    	}, {
    		name: 'organization_name',
    		type: 'string'
    	}
	]
});