Ext.define('Console.model.GasBrandMaster', {
	extend: 'Ext.data.Model',
	fields: [
    	{
            name:'brand_id',
            type:'string'
        },{
            name:'brand_name',
            type:'string'
        },{
            name:'brand_logo',
            type:'string'
        },{
            name:'web_url',
            type:'string'
        },{
            name:'priority',
            type:'string'
        },{
            name:'contract_status',
            type:'string'
        },{
            name:'hand_gasoline_offer',
            type:'Number'
        },{
            name:'self_gasoline_offer',
            type:'Number'
        },{
            name:'diesel_offer',
            type:'Number'
        },{
            name:'reward_point',
            type:'Number'
        },{
            name:'reward_info',
            type:'string'
        },{
            name:'created_date',
            type:'string'
        },{
            name:'updated_date',
            type:'string'
        },{
            name:'operator',
            type:'string'
        }
	]
});