Ext.define('Console.model.betty.RoomPicture',
{
	extend: 'Ext.data.Model',
	fields: [ //對應資料庫
	{
		name:'detail_id',
		type:'String'
	},{
		name:'branch_id',
		type:'String'
	},{
		name:'room_id',
		type:'String'
	},{
		name:'room_name',
		type:'String'
	},{
		name:'detail_sort',
		type:'String'
	},{
		name:'detail_name',
		type:'String'
	},{
		name:'detail_photo',
		type:'String'
	},{
		name:'user_i18n',
		type:'String'
	},{
		name:'created_date',
		type:'String'
	},{
		name:'updated_date',
		type:'String'
	},{
		name:'operator',
		type:'String'
	}
	]
}
);